name: Label Sync

on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  label-sync:
    name: Label sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
